name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install react-scripts@latest && npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
           personal_token: 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
          publish_dir: ./build
